sudo: required
services:
  - docker

before_install:
  - docker build -t krishna/travis-docker -d Dockerfile.dev .

#script should exit by itself, returning 0
script:
  - docker run krishna/travis-docker:v1 npm run test