version: '3'

services: 
  react-web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
    - "3000:3000"
    volumes: 
    - /app/node_modules
    - .:/app
  testing:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
